all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.3.26, mac: 'dc:a6:32:ed:7a:2e', disk: root, network_interface: eth0}
        metal1: {ansible_host: 192.168.3.117, mac: 'dc:a6:32:d4:54:fd', disk: root, network_interface: eth0}
        metal2: {ansible_host: 192.168.3.166, mac: 'dc:a6:32:ed:6e:25', disk: root, network_interface: eth0}
        metal3: {ansible_host: 192.168.3.16, mac: 'dc:a6:32:b9:21:63', disk: root, network_interface: eth0}
    workers:
      hosts:
        metal4: {ansible_host: 192.168.3.130, mac: '54:bf:64:90:00:0a', disk: sda2, network_interface: eth0}
        metal5: {ansible_host: 192.168.3.8, mac: 'a4:bb:6d:3e:ee:3f', disk: nvme0n1p2, network_interface: eth0}
        metal6: {ansible_host: 192.168.3.36, mac: 'e4:54:e8:51:4c:b6', disk: sda2, network_interface: eth0}