app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/openspeedtest/latest
            tag: latest
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 50m
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Speedtest
        hajimari.io/icon: speedometer
      hosts:
        - host: &host speedtest.romelben.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: speedtest-tls-certificate
