---
ntp_stable_os:
  - Debian 11
  - Debian 12
  - Fedora 38
  - Fedora 39
  - Fedora 40

ntp_driftfile: /var/lib/ntp/drift
ntp_server:
  - 0.de.pool.ntp.org
  - 1.de.pool.ntp.org
  - 2.de.pool.ntp.org
  - 3.de.pool.ntp.org

ntp_restrict:
  - "restrict -4 default kod notrap nomodify nopeer noquery limited"
  - "restrict -6 default kod notrap nomodify nopeer noquery limited"
  - "restrict localhost"
  - "restrict 127.0.0.1"

ntp_includefile: false
ntp_statistics: false
