app-template:
  controllers:
    wireguard:
      containers:
        app:
          image:
            repository: lscr.io/linuxserver/wireguard
            tag: latest
          env:
            LOG_CONFS: false
            PEERS: |
              KDDesktop
              KDLaptop
              KDPhone
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
  service:
    wireguard:
      controller: wireguard
      type: LoadBalancer
      ports:
        http:
          port: 51820
          protocol: UDP
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 10Mi
      globalMounts:
        - path: /config
